name: TEST WORKFLOW

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Debug folder structure
        run: ls -R

      - name: Test Python path
        run: python dashboard/report_generator.py
