name: TEST RUN

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Debug files
        run: ls -R

      - name: Run script
        run: python dashboard/report_generator.py
